name: Test Installer Script in English with install all on arm64
on: 
  workflow_dispatch:

jobs:
  test-shell-script:
    runs-on: ubuntu-24.04-arm64
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Run install script in English with install all on arm64
        run: |
          chmod +x ./install.sh
          ./install.sh <<EOF
2          # Language choice: English
1          # Choose to install
y          # System update? Yes
y          # Install Docker? Yes
y          # Enable IPv6 support? Yes
y          # Use default ports? Yes
n          # Manual IP input? No
y          # Install RTMP Server? Yes
y          # Install SRTLA Server? Yes
y          # Install WUD? Yes
y          # Install SLSPanel? Yes
y          # Enable login for SLSPanel? Yes
admin      # Username for SLSPanel admin
password   # Password for SLSPanel admin
EOF
