name: Test Installer Script in German with install all on amd64
on: 
  workflow_dispatch:

jobs:
  test-shell-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Run install script in German with install all on amd64
        run: |
          chmod +x ./install.sh
          ./install.sh <<EOF
          1
          1
          y
          y
          y
          y
          n
          y
          y
          y
          y
          y
          admin
          password
          EOF
